### ISSUE TITLE
Unable to save SVG

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/svgedit_ynh#13]
### Describe the bug

I get an error when I try to save an SVG, "Not allowed to naviagte from top frame to data URL:"data:image/<superlongstring>""

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.5
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: Stable

### Steps to reproduce

   1. *Go to the top left and click "Save"
   2.  See Result

### Expected behavior

The ability to save the SVG would be expected.

### Logs
The app installed fine with no errors in logs

**Comment by Salamandar** [comment]
It should be fixed now with upgrade to v7.
