### ISSUE TITLE
Upgrade from SVG-Edit 2.8.1 to 7.2.0

### ISSUE THREAD

**Issue by marclaporte** [YunoHost-Apps/svgedit_ynh#16]
We can see latest version here: https://github.com/SVG-Edit/svgedit/releases

Thanks!

**Comment by Salamandar** [comment]
@marclaporte i'm currently in the process of upgrading this app. Please vote on https://apps.yunohost.org/app/svgedit so we know people are interested on svgedit ! <3

**Comment by Salamandar** [comment]
Fixed :)
